- id: spike-graphql-linter-schema
  name: spike-graphql-linter-schema
  entry: spike-graphql-linter-schema
  language: node
  args: []
  files: .*(\.graphql)$
  additional_dependencies:
      - graphql-schema-linter@2.0.1
