- id: spike-graphql-linter-schema
  name: spike-graphql-linter-schema
  entry: graphql-schema-linter
  language: node
  'types': [text]
  args: []
  require_serial: false
  additional_dependencies: []  